In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from pandas import Series

## 1.合并数据集
- pd.merge():各种参数的使用

In [3]:
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],\
                   'data1':[i for i in range(7)]})
df2 = DataFrame({'key':['a','b','d'],\
                    'data2':[i for i in range(3)]})
print(df1)

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b


In [4]:
print(df2)

   data2 key
0      0   a
1      1   b
2      2   d


In [5]:
print(pd.merge(df1,df2,on='key') )
#pd1 和 pd2 进行inner联结
#on ：指明将列当做键。默认是重叠的。

   data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0


In [6]:
df3 = DataFrame({'key1':['b','b','a','c','a','a','b'],\
                   'data1':[i for i in range(7)]})
df4 = DataFrame({'key2':['a','b','d'],\
                    'data2':[i for i in range(3)]})
# 如果没有重叠的列名
# 分别指定
print(pd.merge(df3,df4,left_on="key1",right_on='key2'))

   data1 key1  data2 key2
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a


In [7]:
print(pd.merge(df1,df2,how="outer")) # 类似数据库的操作：inner、outer、left、right

   data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0


### 1.1索引上的合并

In [63]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],\
                   'data1':[i for i in range(6)]})
right1 = DataFrame({'group_val':[3.5,7]},index=['a','b'])


In [62]:
print(right1)
print(left1)

   group_val
a        3.5
b        7.0
   data1 key
0      0   a
1      1   b
2      2   a
3      3   a
4      4   b
5      5   c


In [61]:
print(pd.merge(left1,right1,left_on='key',right_index=True))

   data1 key  group_val
0      0   a        3.5
2      2   a        3.5
3      3   a        3.5
1      1   b        7.0
4      4   b        7.0


### 1.2轴向连接

- np.concatenate
- pd.concat([s1,s2,s3])

In [31]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
np.concatenate([arr,arr],axis=1) #numpy对象的方法

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [36]:
s1 = Series([0,1],index=['a','b'])
s2 = Series([2,3,4],index=['c','d','e'])
s3 = Series([5,6],index=['f','g'])

In [37]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [60]:
print(pd.concat([s1,s2,s3],axis=1)) # 按照列

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [48]:
s4 = pd.concat([s1*5,s3])
print(pd.concat([s1,s4],axis=1))
print(pd.concat([s1,s4],axis=1,join="inner")) #取交集
print(pd.concat([s1,s1,s1],keys=['one','two','three']))# 创建层次化索引
print(pd.concat([s1,s1,s1],axis=1,keys=['one','two','three']))# 此时，层次化keys会变成列头

     0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6
   0  1
a  0  0
b  1  5
one    a    0
       b    1
two    a    0
       b    1
three  a    0
       b    1
dtype: int64
   one  two  three
a    0    0      0
b    1    1      1


In [49]:
# 下面展示对于DataFrame的效果
df1 = DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],\
               columns=['one','two'])
df2 = DataFrame(np.arange(4).reshape(2,2),index=['a','c'],\
               columns=['three','four'])
print(df1);print(df2)

   one  two
a    0    1
b    2    3
c    4    5
   three  four
a      0     1
c      2     3


In [50]:
print(pd.concat([df1,df2],axis=1,keys=['level1','level2']))
print(pd.concat([df1,df2],axis=1,keys=['level1','level2'],names=['upper','lower']))

  level1     level2     
     one two  three four
a      0   1    0.0  1.0
b      2   3    NaN  NaN
c      4   5    2.0  3.0
upper level1     level2     
lower    one two  three four
a          0   1    0.0  1.0
b          2   3    NaN  NaN
c          4   5    2.0  3.0


In [51]:
df1 = DataFrame(np.random.randn(3,4),columns=['a','b','c','d'])
df2 = DataFrame(np.random.randn(2,3),columns=['b','d','a'])
print(df1)
print(df2)

          a         b         c         d
0 -0.447944  0.147116  0.342810 -0.618590
1  0.930223  0.379391 -0.994802  0.008333
2 -0.239952  0.150497 -0.603801 -1.153930
          b         d         a
0 -0.332100  0.245658  1.448707
1  1.137389 -0.170095 -1.552497


In [59]:

print(pd.concat([df1,df2]))

print("应该用这种发法")
print(pd.concat([df1,df2],ignore_index=True)) #不保留原来的行索引，产生新的行索引

          a         b         c         d
0 -0.447944  0.147116  0.342810 -0.618590
1  0.930223  0.379391 -0.994802  0.008333
2 -0.239952  0.150497 -0.603801 -1.153930
0  1.448707 -0.332100       NaN  0.245658
1 -1.552497  1.137389       NaN -0.170095
应该用这种发法
          a         b         c         d
0 -0.447944  0.147116  0.342810 -0.618590
1  0.930223  0.379391 -0.994802  0.008333
2 -0.239952  0.150497 -0.603801 -1.153930
3  1.448707 -0.332100       NaN  0.245658
4 -1.552497  1.137389       NaN -0.170095


### 1.4合并重叠数据 

- np.where
- pandas:combine_first

In [70]:
# Array或者Series合并
a = Series([1,2,3,np.nan,4])
b= Series([1,3,3,4,np.nan])
print(np.where(pd.isnull(a),b,a))

[ 1.  2.  3.  4.  4.]


In [72]:
# Pandas提供了combine_first方法
df1 = DataFrame({'a':[1,2,np.nan],\
                'b':[2,3,5],\
                'c':[8,np.nan,0]})
df2 = DataFrame({'a':[5.,4],\
                'b':[np.nan,3.]})
print(df1.combine_first(df2))

     a  b    c
0  1.0  2  8.0
1  2.0  3  NaN
2  NaN  5  0.0


## 2.重塑和轴向旋转

### 2.1重塑层次化索引

- stack：将列旋转为行
- unstack：将行旋转为列
- 默认情况下都是最内层


In [95]:
data = DataFrame(np.arange(6).reshape((2,3)),\
                index=pd.Index(['Ohio','Colorade'],name='state'),\
                columns=pd.Index(['onw','two','three'],name='number'))
print(data)

number    onw  two  three
state                    
Ohio        0    1      2
Colorade    3    4      5


In [82]:
result = data.stack()
print(result)

state     number
Ohio      onw       0
          two       1
          three     2
Colorade  onw       3
          two       4
          three     5
dtype: int32


In [83]:
print(result.unstack()) #我们再重排回去

number    onw  two  three
state                    
Ohio        0    1      2
Colorade    3    4      5


In [92]:
print(result.unstack(1))
print(result.unstack(0))
print(result.unstack('state'))

number    onw  two  three
state                    
Ohio        0    1      2
Colorade    3    4      5
state   Ohio  Colorade
number                
onw        0         3
two        1         4
three      2         5
state   Ohio  Colorade
number                
onw        0         3
two        1         4
three      2         5


### 2.2长格式=>宽格式

数据的格式如下：

![](1.png)

处理成如下形式：

![](2.png)